### ISSUE TITLE
Bad results when trying on token generation

### ISSUE THREAD

**Issue by Ga-Lee** [hutaiHang/ToMe#4]
Hi! Thank you for your effort and contribution!

After reading your interesting paper, I also tried to reproduce the image generation based on certain token ("dog" or the EOT token) as shown in Fig 2, but the results seem unsatisfactory and not as good as in the paper. Therefore, I am confused about the unexpected results, and wondering whether I made certain mistakes during reproducing.

Could you share the implementation details, for example, when generating image with input **token [dog]**,  does it mean we should feed the **single token** instead of the 77-token sequence into both unconditional and conditional UNet?   Are the inputs to unconditional and conditional UNet the same?  

Thank you for your kind explanation and valuable time!

**Comment by hutaiHang** [comment]
Hi, thank you for your attention to our work. Some implementation details are as follows:
When using SDXL, assuming the original prompt_embedding is a 77*2048 matrix obtained by encoding the prompt "a cat with sunglasses and a dog with a hat" through CLIP, we retain only the embedding corresponding to the [dog] token at its index (assumed to be 7) and set the embeddings at other indices to zero:
```python
prompt_embedding[:7] = 0
prompt_embedding[8:] = 0
```
The prompt_embedding remains 77*2048, but the embeddings at non-dog token indices have all been set to zero. We did not manipulate the unconditional prompt_embedding. Then input the edited prompt_embedding , SDXL generates an image of a dog wearing glasses with a probability of about 1/4, as reported in our paper.

**Comment by Ga-Lee** [comment]
Thank you for your sharing and reply!
